### ISSUE TITLE
Feature: User can create  a blog post

### ISSUE THREAD

**Issue by silva-tim** [silva-tim/nomad-ventures#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to create a new blog post

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="681" alt="Screen Shot 2023-07-27 at 4 16 18 PM" src="https://github.com/silva-tim/nomad-ventures/assets/114685872/850a4168-e165-4219-824f-ba07ddb9ea42">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to include create endpoint
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create NavBar 
- [x] Create LinkDrawer
- [x] Create new post page
- [x] Style Form for new post page
- [x] Add fetch call to send new form data to the server so it can be stored in the db

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
